### ISSUE TITLE
Error: Cannot find module '@angular-devkit/core'

### ISSUE THREAD

**Issue by abelardolg** [werthdavid/ngx-zxing#13] opened 2018-01-23 16:24 UTC
Hi,
I have just installed your component but

> `@angular-devkit/core`

is not mentioned in docs.

Kindest regards.

**Comment by abelardolg** [comment] 2018-01-23 16:27
I installed the previous library but this I got this message:

ERROR in ./node_modules/ngx-zxing/ngx-zxing.umd.js
Module not found: Error: Can't resolve 'text-encoding' in '\node_modules\ngx-zxing'

Best regards.

**Comment by werthdavid** [comment] 2018-01-24 09:43
Seems to be a duplicate of #11

**Comment by odahcam** [comment] 2018-01-31 10:32
We just nedd to add this package to devDependencies.

**Comment by odahcam** [comment] 2018-01-31 10:37
@abelardolg for now just run `npm i @angular-devkit/core -D` and it will install the missing package for ya.

**Comment by odahcam** [comment] 2018-01-31 10:41
My develop fork solves this, so soon this will be fixed.

**Comment by odahcam** [comment] 2018-02-14 13:14
Changed the milestone because we have no interest in the v0.3.7.

Closing as resolved in the new milestone.

**Closed by odahcam** 2018-02-14 13:14 UTC
Labels: bug, help wanted
