### ISSUE TITLE
how to handle "Requested device not found" exception?

### ISSUE THREAD

**Issue by praveenrengarajan** [werthdavid/ngx-zxing#25] opened 2018-02-08 07:08 UTC
I'm trying to check whether camera available or not on component OnInit, if no device found have to show the warning message.

`ngOnInit() {

  }
  displayCameras(cameras: object[]) {
      this.availableDevices = cameras;
      if (cameras && cameras.length > 0) {
          this.selectedDevice = cameras[0];
          this.cameraStarted = true;
      } else {
        alert('Please Enable Camera / Camera not found ');
      }
  }`

**Comment by praveenrengarajan** [comment] 2018-02-08 10:12
@odahcam @werthdavid  plz help

**Comment by odahcam** [comment] 2018-02-08 11:35
I'm with the same problem as you and I'm working on it 😄 

You can try the `1.0.0-dev` version which is not that well documented, but has a event `camsNotFound`.

I'll post updates soon :)

**Comment by odahcam** [comment] 2018-02-09 13:43
Almost done!

![image](https://user-images.githubusercontent.com/3942006/36030457-7c810f90-0d8e-11e8-926e-0e38b8700970.png)

**Comment by odahcam** [comment] 2018-02-09 14:59
I will close this now as this issue is a duplicate of #17. Thanks, I see you there.

**Closed by odahcam** 2018-02-09 14:59 UTC
Labels: enhancement, priority: high
